version: "3.8"
services:
  standalone-chrome:
    image: selenium/standalone-chrome:latest
    container_name: standalone-chrome
    privileged: true
    environment:
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_INSTANCES: 15
      SE_NODE_OVERRIDE_MAX_INSTANCES: true
      SE_NODE_MAX_SESSIONS: 15
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      JENKINS_HOME: /var/jenkins_home
      VNC_NO_PASSWORD: 1
    ports:
      - "7900:7900"
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
